### ISSUE TITLE
TODOs and problems to solve

### ISSUE THREAD

**Issue by fabriziogianni7** [fabriziogianni7/mvs-flappy-v2#1]
# Description
Just a todo list to have a sort of mental order for developing this:

## todos

- [ ] #4
- [ ] #5
- [ ] #6

## problems

- [ ] the game is slow if connection is not good
- [ ] need to bring that on chain
- [ ] how can we use a front-end framework?
- [ ] we need to plug the web3 part (connecting wallet and so on)
- [ ] understand how to bring this game on chain (chainlink?)

cc @edakturk14
